#ifndef IntCtrl_Cfg_H
#define IntCtrl_Cfg_H


/*
NVIC_GROUPING_SYSTEM_XXX : GROUPS(7) , SUBGROUPS(0)
NVIC_GROUPING_SYSTEM_XXY : GROUPS(3) , SUBGROUPS(1)
NVIC_GROUPING_SYSTEM_XYY : GROUPS(1) , SUBGROUPS(3)
NVIC_GROUPING_SYSTEM_YYY : GROUPS(0) , SUBGROUPS(7)
*/

#define NVIC_GROUPING_SYSTEM      NVIC_GROUPING_SYSTEM_XXY

#define NVIC_ACTIVATED_INT_SIZE    2

#endif